name: Semgrep Scan

on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4

      - name: Semgrep Scan
        run: |
          semgrep scan --config auto --oss-only --sarif --output=semgrep_output.sarif

      - name: Upload Semgrep Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep_output.sarif
      
      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep_output.sarif
